apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "robomotion.nginx.fullname" . }}
  labels:
    app: {{ template "robomotion.nginx.fullname" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "robomotion.nginx.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ template "robomotion.nginx.fullname" . }}
    spec:
      volumes:      
      - name: nginx-config
        configMap:
          name: nginx-config
      containers:
      - image: nginx
        name: {{ template "robomotion.nginx.fullname" . }}
        volumeMounts:        
        - name:  nginx-config
          mountPath: /etc/nginx/conf.d